/**
 * Generates context/data-model.md from prisma/schema.prisma: a per-model field table,
 * a Mermaid ERD, and a list of migrations. Regex/line-based parsing (no Prisma AST needed
 * for this schema's simple, non-nested style) — see prisma/schema.prisma directly for the
 * authoritative source.
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFileSync, readdirSync } from 'node:fs'
import { writeArtifact } from './lib/manifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
const SCHEMA_PATH = path.join(ROOT, 'prisma', 'schema.prisma')
const MIGRATIONS_DIR = path.join(ROOT, 'prisma', 'migrations')
export const OUTPUT_PATH = path.join(ROOT, 'context', 'data-model.md')

interface FieldInfo {
  name: string
  type: string
  attrs: string
}

interface ModelInfo {
  name: string
  tableName: string
  fields: FieldInfo[]
  blockAttrs: string[]
}

interface EnumInfo {
  name: string
  values: string[]
}

function stripBaseType(type: string): string {
  return type.replace(/\[\]$/, '').replace(/\?$/, '')
}

function parseModels(schema: string): ModelInfo[] {
  const models: ModelInfo[] = []
  const modelRegex = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g
  let match: RegExpExecArray | null
  while ((match = modelRegex.exec(schema))) {
    const [, name, body] = match
    const fields: FieldInfo[] = []
    const blockAttrs: string[] = []
    let tableName = name

    for (const rawLine of body.split('\n')) {
      const line = rawLine.split('//')[0].trim()
      if (!line) continue
      if (line.startsWith('@@')) {
        blockAttrs.push(line)
        const mapMatch = line.match(/@@map\("([^"]+)"\)/)
        if (mapMatch) tableName = mapMatch[1]
        continue
      }
      const fieldMatch = line.match(/^(\w+)\s+([A-Za-z0-9_]+(?:\[\])?\??)\s*(.*)$/)
      if (!fieldMatch) continue
      const [, fieldName, fieldType, attrs] = fieldMatch
      fields.push({ name: fieldName, type: fieldType, attrs: attrs.trim() })
    }

    models.push({ name, tableName, fields, blockAttrs })
  }
  return models
}

function parseEnums(schema: string): EnumInfo[] {
  const enums: EnumInfo[] = []
  const enumRegex = /enum\s+(\w+)\s*\{([\s\S]*?)\n\}/g
  let match: RegExpExecArray | null
  while ((match = enumRegex.exec(schema))) {
    const [, name, body] = match
    const values = body
      .split('\n')
      .map((l) => l.split('//')[0].trim())
      .filter(Boolean)
    enums.push({ name, values })
  }
  return enums
}

function buildErDiagram(models: ModelInfo[]): string {
  const modelNames = new Set(models.map((m) => m.name))
  const edges: string[] = []
  for (const model of models) {
    for (const field of model.fields) {
      const baseType = stripBaseType(field.type)
      if (!modelNames.has(baseType)) continue
      if (!field.attrs.includes('@relation')) continue // skip inverse/back-reference side
      edges.push(`    ${baseType} ||--o{ ${model.name} : "${field.name}"`)
    }
  }
  return ['```mermaid', 'erDiagram', ...edges, '```'].join('\n')
}

function listMigrations(): string[] {
  return readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
}

export function generateDataModel(): { content: string; modelCount: number } {
  const schema = readFileSync(SCHEMA_PATH, 'utf8')
  const models = parseModels(schema)
  const enums = parseEnums(schema)
  const migrations = listMigrations()

  const lines: string[] = [
    '# Data model',
    '',
    '> Generated by `scripts/context/data-model.ts` from `prisma/schema.prisma` — do not',
    '> hand-edit. Run `yarn context:build`. Source of truth is always `prisma/schema.prisma`.',
    '',
    '## Entity-relationship diagram',
    '',
    buildErDiagram(models),
    '',
    '## Models',
    '',
  ]

  for (const model of models) {
    lines.push(`### \`${model.name}\` (table: \`${model.tableName}\`)`, '')
    lines.push('| Field | Type | Attributes |', '| ----- | ---- | ---------- |')
    for (const field of model.fields) {
      lines.push(`| ${field.name} | \`${field.type}\` | ${field.attrs || '—'} |`)
    }
    const otherBlockAttrs = model.blockAttrs.filter((a) => !a.startsWith('@@map'))
    if (otherBlockAttrs.length > 0) {
      lines.push('', `Constraints: ${otherBlockAttrs.map((a) => `\`${a}\``).join(', ')}`)
    }
    lines.push('')
  }

  lines.push('## Enums', '')
  for (const e of enums) {
    lines.push(`- **${e.name}**: ${e.values.join(', ')}`)
  }

  lines.push('', '## Migrations', '')
  for (const m of migrations) {
    lines.push(`- \`${m}\``)
  }
  lines.push('')

  return { content: lines.join('\n'), modelCount: models.length }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { content, modelCount } = generateDataModel()
  const sha256 = writeArtifact(OUTPUT_PATH, content)
  console.log(`Wrote context/data-model.md (${modelCount} models, sha256 ${sha256.slice(0, 12)}...)`)
}
