/**
 * Generates context/module-graph.json (full dependency-cruiser output) and
 * context/module-graph.md (human-readable summary + any architecture-rule violations),
 * enforcing the rules from AGENTS.md:
 * - controllers must not import other controllers
 * - lib/ must not import controllers
 * - middleware must not import controllers
 * - only src/lib/prisma.ts imports @prisma/client
 * - no circular dependencies
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { cruise, type ICruiseOptions, type ICruiseResult, type IModule } from 'dependency-cruiser'
import { stableStringify, writeArtifact } from './lib/manifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
export const JSON_OUTPUT_PATH = path.join(ROOT, 'context', 'module-graph.json')
export const MD_OUTPUT_PATH = path.join(ROOT, 'context', 'module-graph.md')

const cruiseOptions: ICruiseOptions = {
  includeOnly: '^src',
  validate: true,
  tsConfig: { fileName: path.join(ROOT, 'tsconfig.json') },
  ruleSet: {
    forbidden: [
      {
        name: 'no-circular',
        severity: 'error',
        comment: 'No circular dependencies anywhere under src/.',
        from: {},
        to: { circular: true },
      },
      {
        name: 'controllers-no-controller-imports',
        severity: 'error',
        comment:
          'Controllers must not import other controllers (src/controllers/index.ts is exempt — it mounts them; test files are exempt from this rule).',
        from: { path: '^src/controllers', pathNot: ['index\\.ts$', '\\.test\\.ts$'] },
        to: { path: '^src/controllers', pathNot: ['index\\.ts$'] },
      },
      {
        name: 'lib-no-controller-imports',
        severity: 'error',
        comment: 'lib/ must not import controllers.',
        from: { path: '^src/lib' },
        to: { path: '^src/controllers' },
      },
      {
        name: 'middleware-no-controller-imports',
        severity: 'error',
        comment: 'middleware/ must not import controllers.',
        from: { path: '^src/middleware' },
        to: { path: '^src/controllers' },
      },
      {
        name: 'only-prisma-ts-imports-prisma-client',
        severity: 'error',
        comment: 'Only src/lib/prisma.ts may import @prisma/client.',
        from: { path: '^src/(?!lib/prisma\\.ts$)' },
        to: { path: 'node_modules/@prisma/client' },
      },
    ],
  },
}

export async function generateModuleGraph(): Promise<{
  result: ICruiseResult
  violationCount: number
}> {
  const cruiseResult = await cruise([path.join(ROOT, 'src')], cruiseOptions)
  const output = cruiseResult.output as ICruiseResult
  const violations = output.modules.flatMap((m: IModule) =>
    (m.dependencies ?? []).filter((d) => (d.rules ?? []).length > 0)
  )
  return { result: output, violationCount: violations.length }
}

export function buildMarkdownSummary(result: ICruiseResult, violationCount: number): string {
  const lines: string[] = [
    '# Module graph',
    '',
    '> Generated by `scripts/context/module-graph.ts` (dependency-cruiser) — do not',
    '> hand-edit. Run `yarn context:build`. Full graph: `context/module-graph.json`.',
    '',
    `- Modules analyzed: ${result.modules.length}`,
    `- Architecture rule violations: ${violationCount}`,
    '',
  ]

  if (violationCount > 0) {
    lines.push('## Violations', '')
    for (const module of result.modules) {
      for (const dep of module.dependencies ?? []) {
        for (const rule of dep.rules ?? []) {
          lines.push(`- **${rule.name}**: \`${module.source}\` → \`${dep.resolved}\``)
        }
      }
    }
    lines.push('')
  } else {
    lines.push('No violations of the encoded architecture rules. ✅', '')
  }

  return lines.join('\n')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { result, violationCount } = await generateModuleGraph()
  const jsonSha = writeArtifact(JSON_OUTPUT_PATH, stableStringify(result))
  const mdSha = writeArtifact(MD_OUTPUT_PATH, buildMarkdownSummary(result, violationCount))
  console.log(
    `Wrote context/module-graph.json (sha256 ${jsonSha.slice(0, 12)}...) and module-graph.md (sha256 ${mdSha.slice(0, 12)}...)`
  )
  if (violationCount > 0) {
    console.error(`⚠ ${violationCount} architecture rule violation(s) found — see context/module-graph.md`)
    process.exitCode = 1
  }
}
